_target_: rl.successor_features.tabular_sf.SF
alpha: 0.2
gamma: ???
initial_epsilon: 1
final_epsilon: 0.1
epsilon_decay_steps: 10000
use_replay: False
per: False
use_gpi: False
envelope: False
batch_size: 1
buffer_size: 25000
project_name: '{directory}-SFOLS'
log: True
base_values: {}