_target_: rl.successor_features.tabular_sf.SF
alpha: 0.25
gamma: ???
initial_epsilon: 0.6
final_epsilon: 0.1
epsilon_decay_steps: 10000
use_replay: True
per: True
use_gpi: False
envelope: False
batch_size: 5 
buffer_size: 5000
log: True