init:
  log: False
  project_name: SFOLS
  experiment_name: SFOLS

learn:
  total_timesteps: 12000
  use_gpi: True
  eval_freq: 500
  reset_num_timesteps: False
  reset_learning_starts: True
  avg_td_step: ???
  avg_td_threshold: ???