init:
  log: False
  project_name: SFOLS
  experiment_name: SFOLS

learn:
  total_timesteps: 8000
  use_gpi: True
  eval_freq: 500
  reset_num_timesteps: False
  reset_learning_starts: True
  avg_td_step: -1
  avg_td_threshold: -1